spring.datasource.url: jdbc:h2:file:./camunda-h2-database
server:
  port: 8089
camunda.bpm.admin-user:
  id: admin
  password: admin

camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: P1D